# prettier-ignore
name: Lint Code Base

on: [push, pull_request]

jobs:
  run-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env: 
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_HTML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
